# Generated by Django 4.0.4 on 2022-05-15 11:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=25)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoulder', models.FloatField()),
                ('full_length', models.FloatField()),
                ('chest', models.FloatField()),
                ('hip', models.FloatField()),
                ('sl', models.FloatField()),
                ('m', models.FloatField()),
                ('ah', models.FloatField()),
                ('open', models.FloatField()),
                ('thigh', models.FloatField()),
                ('knee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateField(default=datetime.date.today)),
                ('deadline', models.DateField()),
                ('customer_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.measurement')),
            ],
        ),
    ]
