# Generated by Django 4.0.4 on 2022-07-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_category_measurement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='ah',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='chest',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='full_length',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='hip',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='knee',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='m',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='open',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='shoulder',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='sl',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='thigh',
            field=models.FloatField(null=True),
        ),
    ]
