# Generated by Django 4.0.4 on 2022-08-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_measurement_ah_alter_measurement_chest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Complete'), (2, 'Completed')], default=1),
        ),
    ]
