# Generated by Django 4.0.4 on 2022-08-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='measurement',
            name='description',
            field=models.ManyToManyField(to='customer.description'),
        ),
    ]
