# Generated by Django 4.0.4 on 2022-08-10 13:59

import customer.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_description_remove_measurement_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=9)),
                ('status', models.IntegerField(choices=[(1, 'Not Complete'), (2, 'Completed')], default=1)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.description')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(default=customer.models.create_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('vat', models.IntegerField(default=13)),
                ('discount', models.FloatField()),
                ('net_total', models.DecimalField(decimal_places=4, max_digits=9)),
                ('gross_total', models.DecimalField(decimal_places=4, max_digits=9)),
                ('status', models.IntegerField(choices=[(1, 'Paid'), (2, 'Not Paid')], default=2)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.order')),
                ('orderdes', models.ManyToManyField(to='customer.ordereddescription')),
            ],
        ),
    ]
