# Generated by Django 4.0.4 on 2022-08-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_invoice_gross_total_alter_invoice_net_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid'), ('Partially Paid', 'Partially Paid')], default='Not Paid', max_length=25),
        ),
    ]
