# Generated by Django 4.0.4 on 2022-08-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not Complete', 'Not Complete'), ('Complete', 'Completed')], default='Not Complete', max_length=25),
        ),
        migrations.AlterField(
            model_name='ordereddescription',
            name='status',
            field=models.CharField(choices=[('Not Complete', 'Not Complete'), ('Complete', 'Completed')], default='Not Complete', max_length=25),
        ),
    ]
