# Generated by Django 4.0.4 on 2022-08-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_order_status_alter_ordereddescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='emp_status',
            field=models.CharField(choices=[('NA', 'NA'), ('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT')], default='NA', max_length=25),
        ),
    ]
