# Generated by Django 4.0.4 on 2022-08-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_order_emp_status_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Assigned', 'Assigned'), ('Accepted', 'Accepted'), ('Complete', 'Completed')], default='Assigned', max_length=25),
        ),
        migrations.AlterField(
            model_name='ordereddescription',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Assigned', 'Assigned'), ('Accepted', 'Accepted'), ('Complete', 'Completed')], default='Not Complete', max_length=25),
        ),
    ]
