# Generated by Django 4.0.3 on 2022-08-23 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_order_status_alter_ordereddescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='check_in',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
