# Generated by Django 4.0.3 on 2022-07-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('number', models.IntegerField()),
                ('address', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=256)),
                ('image', models.ImageField(max_length=255, null=True, upload_to='')),
                ('role', models.CharField(max_length=25)),
                ('vendor', models.CharField(max_length=25)),
            ],
        ),
    ]
