# Generated by Django 4.0.4 on 2022-05-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeeorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeOrder',
        ),
    ]
