# Generated by Django 4.0.4 on 2022-05-15 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_vendor_address_vendor_logo_vendor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.vendor'),
            preserve_default=False,
        ),
    ]
